version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kokodi
      POSTGRES_USER: kokodi
      POSTGRES_PASSWORD: kokodi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kokodi
      SPRING_DATASOURCE_USERNAME: kokodi
      SPRING_DATASOURCE_PASSWORD: kokodi
    ports:
      - "8080:8080"

volumes:
  postgres_data: 